version: "3"

services:

  dh-postgres:
    image: postgres:11
    volumes:
      - dh_web_testing:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file: .env

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "dh-postgres"
    command: "dh-postgres:${POSTGRES_PORT}"

  dh-web:
    build: .
    restart: always
    command: "bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - .:/vol/dh
      - dh_static_files:/vol/static_files
    ports:
      - "8000:8000"
    links:
      - "dh-postgres:dh-postgres"
    env_file: .env
    depends_on:
      - start_dependencies

  dh-nginx:
    build: nginx
    restart: always
    volumes:
      - dh_static_files:/vol/static_files
    ports:
      - "4000:4000"
    links:
      - "dh-web:dh-web"
    depends_on:
      - start_dependencies
      - dh-web

volumes:
  dh_web_testing:
  dh_static_files:
