version: "3"

services:
  postgres:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    env_file: .env

  app:
    build: dh_abstracts
    restart: always
    command: "bash -c ${SERVE_COMMAND}"
    volumes:
      - ./dh_abstracts:/vol/dh
      - static:/vol/static_files
      - ./data:/vol/data
    expose:
      - 8000
    ports:
      - "25:25"
    links:
      - "postgres:postgres"
      - "memcached:memcached"
    env_file: .env
    depends_on:
      - postgres
      - memcached

  memcached:
    image: memcached:1.6.5
    restart: always
    expose:
      - 11211

  nginx:
    image: nginx:1.16.1
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d/.
      - static:/vol/static_files
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    links:
      - "app:app"
    depends_on:
      - app

volumes:
  db:
  static:
