version: "3"

services:
  postgres:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - 5432
    env_file: .env

  app:
    build: .
    restart: always
    command: "bash -c ${SERVE_COMMAND}"
    volumes:
      - .:/vol/dh
      - static:/vol/static_files
    expose:
      - 8000
    links:
      - "postgres:postgres"
    env_file: .env
    depends_on:
      - postgres

  nginx:
    image: nginx:1.16.1
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d/.
      - static:/vol/static_files
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    links:
      - "app:app"
    depends_on:
      - app

volumes:
  db:
  static:
