# Generated by Django 2.1 on 2018-12-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('work', 'authorship_order'), ('author', 'work')},
        ),
    ]
