# Generated by Django 2.1 on 2018-12-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appellation',
            unique_together={('author', 'first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentassertion',
            unique_together={('author', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='genderassertion',
            unique_together={('author', 'gender')},
        ),
        migrations.AlterUniqueTogether(
            name='institutionassertion',
            unique_together={('author', 'institution')},
        ),
    ]
