# Generated by Django 2.1 on 2018-11-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_memberships', to='abstracts.Conference')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_memberships', to='abstracts.ConferenceSeries')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='series',
            field=models.ManyToManyField(through='abstracts.SeriesMembership', to='abstracts.ConferenceSeries'),
        ),
    ]
