# Generated by Django 2.1 on 2018-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_auto_20181221_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorship',
            name='departments',
            field=models.ManyToManyField(related_name='asserted_by', to='abstracts.Department'),
        ),
    ]
