# Generated by Django 2.1 on 2018-12-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_auto_20181219_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
