# Generated by Django 2.1 on 2018-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0003_auto_20181109_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
