# Generated by Django 2.1 on 2018-12-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0003_authorship_departments'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentassertion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='departmentassertion',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='departmentassertion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='departmentassertion',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='genderassertion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='genderassertion',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='genderassertion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='genderassertion',
            name='gender',
        ),
        migrations.AlterUniqueTogether(
            name='institutionassertion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='institutionassertion',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='institutionassertion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='institutionassertion',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='appellation',
            name='asserted_by',
        ),
        migrations.RemoveField(
            model_name='author',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='author',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='author',
            name='institutions',
        ),
        migrations.AddField(
            model_name='authorship',
            name='appellations',
            field=models.ManyToManyField(related_name='asserted_by', to='abstracts.Appellation'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='genders',
            field=models.ManyToManyField(related_name='asserted_by', to='abstracts.Gender'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='institutions',
            field=models.ManyToManyField(related_name='asserted_by', to='abstracts.Institution'),
        ),
        migrations.DeleteModel(
            name='DepartmentAssertion',
        ),
        migrations.DeleteModel(
            name='GenderAssertion',
        ),
        migrations.DeleteModel(
            name='InstitutionAssertion',
        ),
    ]
