# Generated by Django 2.1 on 2019-04-29 21:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0004_auto_20190429_1712'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='work',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='abstracts_w_search__cfd9ce_gin'),
        ),
    ]
