# Generated by Django 2.1 on 2018-12-23 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0004_auto_20181222_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstracts.Author'),
        ),
    ]
