# Generated by Django 2.1 on 2018-12-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0005_auto_20181222_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorship',
            name='appellations',
            field=models.ManyToManyField(blank=True, related_name='asserted_by', to='abstracts.Appellation'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='asserted_by', to='abstracts.Department'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='genders',
            field=models.ManyToManyField(blank=True, related_name='asserted_by', to='abstracts.Gender'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='institutions',
            field=models.ManyToManyField(blank=True, related_name='asserted_by', to='abstracts.Institution'),
        ),
    ]
