# Generated by Django 2.1 on 2018-12-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0006_auto_20181224_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='conferences_organized',
            field=models.ManyToManyField(blank=True, related_name='organizers', to='abstracts.Conference'),
        ),
    ]
