# Generated by Django 2.1 on 2018-11-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0006_auto_20181109_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='versions',
            field=models.ManyToManyField(related_name='author', through='abstracts.Authorship', to='abstracts.Version'),
        ),
    ]
