# Generated by Django 2.1 on 2018-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0007_author_versions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='appellations',
            field=models.ManyToManyField(related_name='authors', through='abstracts.AppellationAssertion', to='abstracts.Appellation'),
        ),
        migrations.AlterField(
            model_name='author',
            name='versions',
            field=models.ManyToManyField(related_name='authors', through='abstracts.Authorship', to='abstracts.Version'),
        ),
    ]
