# Generated by Django 2.2 on 2019-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0008_auto_20190430_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='conferences', through='abstracts.SeriesMembership', to='abstracts.ConferenceSeries'),
        ),
    ]
