# Generated by Django 2.1 on 2018-11-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0008_auto_20181112_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='series',
            field=models.ManyToManyField(related_name='conferences', through='abstracts.SeriesMembership', to='abstracts.ConferenceSeries'),
        ),
    ]
