# Generated by Django 2.1 on 2018-11-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0010_auto_20181112_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='title',
            new_name='name',
        ),
    ]
