# Generated by Django 2.2 on 2019-05-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0010_auto_20190507_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesmembership',
            name='number',
            field=models.IntegerField(blank=True, help_text='Order of this conference within this series.', null=True),
        ),
    ]
