# Generated by Django 2.1 on 2018-12-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0010_auto_20181229_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
