# Generated by Django 2.2 on 2019-05-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0011_seriesmembership_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seriesmembership',
            unique_together={('series', 'conference')},
        ),
    ]
