# Generated by Django 2.1 on 2018-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0011_auto_20181119_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesmembership',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seriesmembership',
            unique_together={('series', 'number')},
        ),
    ]
