# Generated by Django 2.1 on 2018-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0012_auto_20181120_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
