# Generated by Django 2.1 on 2018-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0013_organizer_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='notes',
        ),
        migrations.AddField(
            model_name='conferenceseries',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
