# Generated by Django 2.2 on 2019-06-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0014_auto_20190523_1209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('year', 'venue')},
        ),
    ]
