# Generated by Django 2.1 on 2018-12-30 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0014_auto_20181230_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['title']},
        ),
    ]
