# Generated by Django 2.1 on 2018-12-31 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0015_auto_20181230_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['authorships__appellations__last_name']},
        ),
    ]
