# Generated by Django 2.1 on 2018-12-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0016_auto_20181230_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='conferenceseries',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='organizer',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
