# Generated by Django 2.1 on 2018-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0018_auto_20181230_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceseries',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
