# Generated by Django 2.1 on 2018-11-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0020_auto_20181122_2043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('author', 'version'), ('version', 'authorship_order')},
        ),
    ]
