# Generated by Django 2.1 on 2018-11-23 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0021_auto_20181122_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='versions', to='abstracts.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('author', 'version', 'authorship_order')},
        ),
    ]
