# Generated by Django 2.1 on 2018-12-31 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0022_remove_work_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='appellations',
            field=models.ManyToManyField(related_name='authors', through='abstracts.Authorship', to='abstracts.Appellation'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='appellation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abstracts.Appellation'),
            preserve_default=False,
        ),
    ]
