# Generated by Django 2.1 on 2018-11-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0022_auto_20181122_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorship',
            name='authorship_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
