# Generated by Django 2.1 on 2019-01-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0023_auto_20181231_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['appellations__last_name']},
        ),
    ]
