# Generated by Django 2.1 on 2018-12-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0024_auto_20181122_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='full_text_type',
            field=models.CharField(choices=[('xml', 'XML'), ('txt', 'plain text')], default='txt', max_length=3),
        ),
    ]
