# Generated by Django 2.1 on 2019-01-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0024_auto_20190101_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorship',
            name='appellations',
        ),
    ]
