# Generated by Django 2.1 on 2019-01-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0025_remove_authorship_appellations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorship',
            name='appellation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asserted_by', to='abstracts.Appellation'),
        ),
    ]
