# Generated by Django 2.1 on 2019-01-02 18:43

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0028_auto_20190101_2158'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='work',
            name='full_text_idx',
        ),
        migrations.RemoveField(
            model_name='work',
            name='search_vector',
        ),
        migrations.AddIndex(
            model_name='work',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_text'], name='full_text_idx'),
        ),
    ]
