# Generated by Django 2.1 on 2019-01-02 19:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0029_auto_20190102_1343'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='work',
            name='full_text_idx',
        ),
        migrations.AddField(
            model_name='work',
            name='search_text',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='work',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='full_text_idx'),
        ),
    ]
