# Generated by Django 2.1 on 2018-12-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0029_auto_20181218_1000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
