# Generated by Django 2.1 on 2019-01-02 20:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0031_auto_20190102_1419'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='author_text_idx',
        ),
        migrations.RemoveField(
            model_name='author',
            name='search_text',
        ),
        migrations.AddField(
            model_name='appellation',
            name='search_text',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='appellation',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='appellation_idx'),
        ),
    ]
