# Generated by Django 2.1 on 2019-01-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0033_auto_20190102_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appellation',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
