# Generated by Django 2.1 on 2019-01-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0034_auto_20190103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
