# Generated by Django 2.1 on 2019-01-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0035_auto_20190103_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
