# Generated by Django 2.1 on 2019-01-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0036_organizer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
