# Generated by Django 2.1 on 2019-01-04 16:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0037_auto_20190103_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='search_text',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='abstracts_i_search__bb6726_gin'),
        ),
    ]
