# Generated by Django 2.1 on 2019-01-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0038_auto_20190104_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-year']},
        ),
    ]
