# Generated by Django 2.1 on 2019-01-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0039_auto_20190104_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceseries',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
