# Generated by Django 2.1 on 2019-01-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0040_auto_20190104_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
