# Generated by Django 2.1 on 2019-01-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0041_auto_20190105_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileImportMessgaes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('addition_type', models.CharField(choices=[('mat', 'matched existing'), ('new', 'newly created')], max_length=3)),
                ('warning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileImportTries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstracts.Conference')),
                ('file_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstracts.FileImport')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='abstracts.Conference'),
        ),
        migrations.AddField(
            model_name='fileimportmessgaes',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abstracts.FileImportTries'),
        ),
    ]
