# Generated by Django 2.1 on 2019-01-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0042_auto_20190106_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimportmessgaes',
            name='addition_type',
            field=models.CharField(blank=True, choices=[('mat', 'matched existing'), ('new', 'newly created')], max_length=3),
        ),
    ]
