# Generated by Django 2.1 on 2019-01-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0043_auto_20190106_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimportmessgaes',
            name='addition_type',
            field=models.CharField(choices=[('mat', 'matched existing'), ('new', 'newly created'), ('non', 'NA')], max_length=3),
        ),
    ]
