# Generated by Django 2.1 on 2019-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0045_auto_20190106_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together={('name', 'country')},
        ),
    ]
