# Generated by Django 2.1 on 2019-01-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0046_auto_20190106_0942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institution',
            unique_together=set(),
        ),
    ]
