# Generated by Django 2.1 on 2019-01-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0050_auto_20190107_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgn_id', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='abstracts.Nation')),
            ],
        ),
        migrations.AddField(
            model_name='nation',
            name='pref_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_reference_to', to='abstracts.NationLabel'),
        ),
    ]
