# Generated by Django 2.1 on 2019-01-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0051_auto_20190108_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='pref_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferred_reference_to', to='abstracts.NationLabel'),
        ),
    ]
