# Generated by Django 2.1 on 2019-04-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='abbreviation',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
