# Generated by Django 2.1 on 2019-04-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_auto_20190428_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceseries',
            name='abbreviation',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
