# Generated by Django 2.1 on 2019-04-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0005_auto_20190429_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appellation',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
