# Generated by Django 2.1 on 2019-04-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0007_auto_20190429_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
    ]
