# Generated by Django 3.0.4 on 2020-03-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0015_auto_20190603_1430'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorship',
            unique_together={('author', 'work')},
        ),
    ]
