# Generated by Django 3.0.4 on 2020-03-31 21:15

from django.db import migrations


def remove_unpublished(apps, schema_editor):
    # Remove every abstract that is set as a submitted work
    Work = apps.get_model("abstracts", "Work")
    Work.objects.filter(state="su").delete()


class Migration(migrations.Migration):

    dependencies = [("abstracts", "0017_auto_20200331_1642")]

    operations = [migrations.RunPython(remove_unpublished)]
