# Generated by Django 3.0.4 on 2020-03-31 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0018_auto_20200331_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='published_version',
        ),
        migrations.RemoveField(
            model_name='work',
            name='state',
        ),
    ]
