# Generated by Django 3.0.4 on 2020-04-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0019_auto_20200331_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorship',
            name='genders',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
