# Generated by Django 3.0.4 on 2020-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0020_auto_20200401_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
