# Generated by Django 3.0.4 on 2020-04-01 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abstracts', '0022_auto_20200401_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='user_last_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_last_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
