# Generated by Django 3.0.5 on 2020-04-06 17:28

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0026_auto_20200403_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='search_text',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
    ]
