# Generated by Django 3.0.5 on 2020-04-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0028_auto_20200414_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='parent_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_papers', to='abstracts.Work'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='is_parent',
            field=models.BooleanField(db_index=True, default=False, help_text="Works of this type are considered multi-paper panels/sessions and may contain 'child' abstracts"),
        ),
    ]
