# Generated by Django 3.0.5 on 2020-04-24 16:11

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('abstracts', '0030_auto_20200421_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='abstracts.Conference')),
                ('document', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_conference', to='filer.File')),
            ],
        ),
    ]
