# Generated by Django 3.0.5 on 2020-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0033_conference_full_text_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='full_text_public',
            field=models.BooleanField(db_index=True, default=False, help_text="Should the full text for this conference's abstracts be publicly available?"),
        ),
    ]
