# Generated by Django 3.0.5 on 2020-04-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0036_auto_20200429_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='conference',
            field=models.ForeignKey(help_text='The conference where this abstract was submitted/published.', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='abstracts.Conference'),
        ),
        migrations.AlterField(
            model_name='work',
            name='disciplines',
            field=models.ManyToManyField(blank=True, help_text='Optional discipline tag from a controlled vocabulary established by the ADHO DH conferences.', related_name='works', to='abstracts.Discipline'),
        ),
        migrations.AlterField(
            model_name='work',
            name='full_text_license',
            field=models.ForeignKey(blank=True, help_text='License of this full text, when known', null=True, on_delete=django.db.models.deletion.SET_NULL, to='abstracts.License'),
        ),
        migrations.AlterField(
            model_name='work',
            name='full_text_type',
            field=models.CharField(blank=True, choices=[('', '-----------'), ('xml', 'XML'), ('txt', 'plain text')], default='', help_text='Format of the full text (currently either plain text, or XML)', max_length=3),
        ),
        migrations.AlterField(
            model_name='work',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Optional keywords that are supplied by authors during submission.', related_name='works', to='abstracts.Keyword'),
        ),
        migrations.AlterField(
            model_name='work',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text="The language(s) of the text of an abstract (not to be confused with e.g. 'English' as a keyword, where the topic of the abstract concerns English.)", related_name='works', to='abstracts.Language'),
        ),
        migrations.AlterField(
            model_name='work',
            name='parent_session',
            field=models.ForeignKey(help_text='If this work was part of a multi-paper organized session, this is the entry for the parent session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_papers', to='abstracts.Work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(db_index=True, help_text='Abstract title', max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Optional topics from a controlled vocabulary established by the ADHO DH conferences.', related_name='works', to='abstracts.Topic'),
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, help_text='URL where the full text of this specific abstract can be freely accessed', max_length=500),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(blank=True, help_text='Abstracts may belong to one type that has been defined by editors based on a survey of all the abstracts in this collection, e.g. "poster", "workshop", "long paper".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='abstracts.WorkType'),
        ),
    ]
