# Generated by Django 3.0.5 on 2020-04-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0037_auto_20200430_1034'),
        ('abstracts', '0037_auto_20200429_1208'),
    ]

    operations = [
    ]
