# Generated by Django 3.0.5 on 2020-04-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0039_auto_20200430_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(help_text='Abstracts may belong to one type that has been defined by editors based on a survey of all the abstracts in this collection, e.g. "poster", "workshop", "long paper".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='abstracts.WorkType'),
        ),
    ]
