# Generated by Django 3.0.5 on 2020-04-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0040_auto_20200430_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='venue',
            new_name='short_title',
        ),
        migrations.AlterUniqueTogether(
            name='conference',
            unique_together={('year', 'short_title')},
        ),
    ]
