# Generated by Django 3.0.5 on 2020-04-30 16:06

from django.db import migrations
from django.db.models import F


def transfer_abbreviations(apps, schema_editor):
    # If a conference has an abbreviation, use it to replace the short_title
    Conference = apps.get_model("abstracts", "Conference")
    Conference.objects.exclude(venue_abbreviation="").update(
        short_title=F("venue_abbreviation")
    )


class Migration(migrations.Migration):

    dependencies = [("abstracts", "0041_auto_20200430_1153")]

    operations = [migrations.RunPython(transfer_abbreviations)]
