# Generated by Django 3.0.5 on 2020-04-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0042_auto_20200430_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='venue_abbreviation',
        ),
    ]
