# Generated by Django 3.0.5 on 2020-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0044_auto_20200430_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City where the conference took place', max_length=1000),
        ),
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(blank=True, help_text='MM/DD/YYY', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='hosting_institutions',
            field=models.ManyToManyField(blank=True, help_text='Institutions that organized the conference', related_name='conferences', to='abstracts.Institution'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Further descriptive information'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='series',
            field=models.ManyToManyField(blank=True, help_text='Conference series which this event belongs to', related_name='conferences', through='abstracts.SeriesMembership', to='abstracts.ConferenceSeries'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='short_title',
            field=models.CharField(help_text='A location-based short title for the conference', max_length=200),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(blank=True, help_text='MM/DD/YYY', null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state_province_region',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='State / Province / Region'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='theme_title',
            field=models.CharField(blank=True, default='', help_text="Optional thematic title (e.g. 'Big Tent Digital Humanities')", max_length=1000),
        ),
        migrations.AlterField(
            model_name='conference',
            name='url',
            field=models.URLField(blank=True, help_text='Public URL for the conference and/or conference program', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='year',
            field=models.PositiveIntegerField(help_text='Year the conference was held'),
        ),
    ]
