# Generated by Django 3.0.5 on 2020-05-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0052_auto_20200501_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='primary_contact',
        ),
    ]
