# Generated by Django 3.0.5 on 2020-05-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0054_conference_entry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='full_text',
            field=models.TextField(blank=True, default='', help_text='Full text content of the abstract, including references, but excluding authorship information.', max_length=500000),
        ),
    ]
