# Generated by Django 3.0.5 on 2020-05-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0058_conference_editing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['abbreviation']},
        ),
    ]
