# Generated by Django 3.0.5 on 2020-05-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0063_institution_state_province_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='department',
            field=models.CharField(blank=True, default='', help_text='The name of a department, center, or other subdivision of a larger institution', max_length=500),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(help_text='The parent institution for this affiliation', on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='abstracts.Institution'),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Surname and/or first and middle initials', max_length=100),
        ),
        migrations.AlterField(
            model_name='appellation',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Family name', max_length=100),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='affiliations',
            field=models.ManyToManyField(blank=True, help_text='The affiliation(s) given by the author when they submitted this particular work.', related_name='asserted_by', to='abstracts.Affiliation'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='appellation',
            field=models.ForeignKey(help_text='The appellation given by the author when they submitted this particular work.', on_delete=django.db.models.deletion.CASCADE, related_name='asserted_by', to='abstracts.Appellation'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(help_text='The author', on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='abstracts.Author'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='authorship_order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Authorship order (1-based indexing)'),
        ),
        migrations.AlterField(
            model_name='authorship',
            name='work',
            field=models.ForeignKey(help_text='The work authored.', on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='abstracts.Work'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='state_province_region',
            field=models.CharField(blank=True, default='', help_text='State, province, or region where the conference was held', max_length=1000, verbose_name='State / Province / Region'),
        ),
        migrations.AlterField(
            model_name='conferenceseries',
            name='abbreviation',
            field=models.CharField(help_text='Display abbreviation', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='conferenceseries',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Discursive notes, generally concerning the history of this series'),
        ),
        migrations.AlterField(
            model_name='conferenceseries',
            name='title',
            field=models.CharField(help_text='Full name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='pref_name',
            field=models.CharField(db_index=True, help_text='Preferred label for the country sourced from the Getty TGN', max_length=300),
        ),
        migrations.AlterField(
            model_name='country',
            name='tgn_id',
            field=models.URLField(help_text='Canonical ID in the Getty Thesaurus of Geographic Names', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City where the institution is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country where the institution is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='abstracts.Country'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Institution name', max_length=500),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state_province_region',
            field=models.CharField(blank=True, default='', help_text='State, province, or region where the institution is located', max_length=1000, verbose_name='State / Province / Region'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='author_supplied',
            field=models.BooleanField(default=True, help_text='Was this keyword supplied by an author, or applied by an editor?'),
        ),
        migrations.AlterField(
            model_name='license',
            name='display_abbreviation',
            field=models.CharField(help_text='A short, identifiable abbreviation of the license', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='full_text',
            field=models.TextField(help_text='Full text of the license', max_length=100000),
        ),
        migrations.AlterField(
            model_name='license',
            name='title',
            field=models.CharField(help_text='Full title of the license', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.URLField(blank=True, help_text='URL with a full description of the licnese', null=True),
        ),
    ]
