# Generated by Django 3.0.5 on 2020-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abstracts", "0066_auto_20200728_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="full_text_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Should the full text for this conference's abstracts be publicly available, no matter the individual abstract's license status?",
            ),
        ),
    ]
