# Generated by Django 3.0.5 on 2020-08-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0067_auto_20200814_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='disciplines',
            field=models.ManyToManyField(blank=True, help_text='Optional discipline tag from a controlled vocabulary established by the ADHO DH conferences. (Matches ANY of the disciplines)', related_name='works', to='abstracts.Discipline'),
        ),
        migrations.AlterField(
            model_name='work',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='Optional keywords that are supplied by authors during submission. (Matches ANY of the keywords)', related_name='works', to='abstracts.Keyword'),
        ),
        migrations.AlterField(
            model_name='work',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text="The language(s) of the text of an abstract (not to be confused with e.g. 'English' as a keyword, where the topic of the abstract concerns English.)  (Matches ANY of the languages)", related_name='works', to='abstracts.Language'),
        ),
        migrations.AlterField(
            model_name='work',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Optional topics from a controlled vocabulary established by the ADHO DH conferences. (Matches ANY of the topics)', related_name='works', to='abstracts.Topic'),
        ),
    ]
