# Generated by Django 3.0.5 on 2020-08-19 17:06

from django.db import migrations, transaction
from django.db.models.functions import Lower


@transaction.atomic
def merge_disciplines_to_topics(apps, schema_editor):
    Discipline = apps.get_model("abstracts", "Discipline")
    Topic = apps.get_model("abstracts", "Topic")
    Work = apps.get_model("abstracts", "Work")

    for d in Discipline.objects.all():
        topic = Topic.objects.get_or_create(title=d.title.lower())
        for w in Work.objects.filter(disciplines=d).exclude(topics=topic[0]):
            w.topics.add(topic[0])
            w.save()
        d.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("abstracts", "0068_auto_20200818_1359"),
    ]

    operations = [migrations.RunPython(merge_disciplines_to_topics)]
