# Generated by Django 3.0.5 on 2020-08-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0069_auto_20200819_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='disciplines',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
    ]
