# Generated by Django 3.0.5 on 2020-08-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0070_auto_20200819_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='full_text_public',
        ),
    ]
