# Generated by Django 3.0.10 on 2020-09-21 20:42

from django.db import migrations


def generate_conference_search_text(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Conference = apps.get_model("abstracts", "Conference")
    for conf in Conference.objects.all():
        conf.search_text = " ".join(
            [str(conf.year), conf.short_title, conf.city]
            + [str(hi) for hi in conf.hosting_institutions.all()]
            + [" ".join([sr.title, sr.abbreviation]) for sr in conf.series.all()]
            + [" ".join([sr.name, sr.abbreviation]) for sr in conf.organizers.all()]
        )
        conf.save()


class Migration(migrations.Migration):

    dependencies = [
        ("abstracts", "0072_conference_search_text"),
    ]

    operations = [migrations.RunPython(generate_conference_search_text)]
